### ISSUE TITLE
(Feature - Infraestructure) Creación de Pub/sub GCP

### ISSUE THREAD

**Issue by zkodah** [TSSW2024/Sprint-3#11]
## Descripción
Implementar una suscripción Pub/Sub en el backend para procesar mensajes de un tema específico en tiempo real.

## Tareas
* [x] GCP:  Configurar el entorno de desarrollo para usar las bibliotecas de cliente de GCP
* [x] Tema:  Crear una suscripción al tema Pub/Sub recién creado
* [x] Mensaje:  Implementar la lógica  de procesamiento de mensajes en el backend
* [x] Prueba:  Realizar pruebas para validar la correcta recepción y manejo de mensajes
* [x] Configurar:  Documentar el proceso de configuración y uso de la suscripción

> 

## Fecha de Vencimiento
Se ha definido la fecha de entrega para el día 19-05-2024

**Comment by JoseMalcaR** [comment]
## Creacion del tema y la suscripcion.

Para crear el tema y la suscripcion nos dirigiremos al servicio de PUB/SUB en GCP, se puede hacer de dos formas, la primera es directamente en GCP y la que use yo seria a travez de la consola integrada(cloudshell) en GCP.

Una vez abierta la consola, ejecutaremos los siguientes comandos:

Para inicializar ejecutaremos el siguiente comando: 

```bash
gloud init
```

Una vez estemos adentro seleccionamos nuestra cuenta de GCP.

Despues nos mostrara una lista de los proyectos asociados a nuestro usuario, donde escogeremos en este caso tss-1s2024.

Nos preguntara si deseamos configurar una region y zona de computo,de momento ponemos que no(n).

Una vez adentro del proyecto, procedemos a crear el tema de PUB/SUB con el siguiente comando:

```bash
gcloud pubsub topics create my-topic
```

Y por ultimo creamos la suscripcion para poder trabajar con los mensajes publicaods en el tema con el siguiente comando:

```bash
gcloud pubsub subscriptions create my-sub --topic my-topic
```

## Uso de la Suscripcion

Para poder usar la suscripcion nos dirigiremos a la parte izquierda en temas y seleccionaremos el creado, en este caso my-topic, 
en el **Paso 1** pulsaremos mensajes para poder publicar uno, creamos el mensaje y en el **Paso 2** seleccionaremos la suscripcion que creamos en este caso my-sub.

Y por ultimo para poder extraerlo y que se muestre en nuestro main.go pulsaremos en **Extraer**.
![PS](https://github.com/TSSW2024/Sprint-3/assets/165086815/54a7b9c4-7164-4a5d-852c-97df89a3f0ee)
