### ISSUE TITLE
 (Spike - Qa) Brechas de seguridad

### ISSUE THREAD

**Issue by zkodah** [TSSW2024/Sprint-3#17]
## Descripción
Este Spike tiene como objetivo realizar un análisis exhaustivo de la seguridad de nuestras cargas de trabajo en la nube, identificar posibles brechas de seguridad y desarrollar estrategias para mitigar riesgos.

## Tareas
* [x] : Conceptos Claves, Amenazas de WorkLoads
* [x] : Identificar los controles de acceso y las políticas de seguridad a implementar
* [x] : Investigar y evaluar herramientas de seguridad adicionales para la protección de workloads.
* [x] : Proponer mejoras en la configuración de seguridad

## Fecha de Vencimiento
Se ha definido la fecha de entrega para el día 26-05-2024

**Comment by VlackVist** [comment]
Al estar en una fase temprana no pueden realizarse pruebas o análisis de bitácora de la app por lo que el enfoque será ir teniendo en cuenta las amenazas básicas y a las que se enfrenta Binance que es un buen modelo para tomar de ejemplo de predicción de vulnerabilidades.
Conceptos claves a tener en cuenta para entender las amenazas de WorkLoads:
- Ataque distribuido de denegación de servicio (DDoS): es un tipo de ciberataque, en el que un atacante sobrecarga un sitio web, un servidor o un recurso de red con tráfico malicioso.
- Inyección de SQL: corresponde a un tipo de ciberataque encubierto en el cual un hacker inserta código propio en un sitio web con el fin de quebrantar las medidas de seguridad y acceder a datos protegidos (Comúnmente utilizado en métodos que permiten la subida de archivos)
- Herramientas de ingeniería social: Son todo tipo de herramientas que buscan apelar a las vulnerabilidades que se expone el humano al convivir en sociedad. Principalmente para este caso se hace referencia a los ataques de phising mediante sitios web falsos idénticos a la app que quiere ser vulnerada.

**Comment by VlackVist** [comment]
Bajo la premisa anterior hay que entender que si por algún motivo buscamos permitir la subida de archivos debe ser controlada. Esto porque se pueden dar ataques por distintos métodos pero uno frecuente es aprovechar las vulnerabilidades no revisadas al momento de permitir la subida de archivos. Un ejemplo sería que el atacante intente utilizar el método de actualizar la imagen del perfil para subir un tipo de archivo distinto y/o malicioso, el cual permita exponer algún puerto o tipo de puerta trasera dentro de nuestro sistema. 

También hay que ser muy cuidadosos cuando se trabaje con la base de datos y sobre todo no exponer campos de la base de datos dentro del código o dentro de directorios del sistema. Ya que como se mencionó siempre pueden realizarse inyecciones sql para intentar infectar nuestra base de datos o la aplicación en sí.

**Comment by VlackVist** [comment]
Existen distintas herramientas útiles con las cuales podemos medir el rendimiento de nuestro sistema y como se desempeña. Pero ¿Por qué sería esto importante con la seguridad? pues ya que siempre se pueden aprovechar de cualquier tipo de vulneración para atacar el sistema. 
Por ejemplo si tenemos una mala gestión de memoria al realizar algún proceso de registro un atacante podría realizar un ataque masivo en el que intente registrarse en la aplicación lo cual en cosa de segundos o minutos puede provocar la caída de nuestro sistema provocando que deba reiniciarse todo (Lo cual claramente debe ser evitado a toda costa debido al peso de la aplicación que se está montando).

Al mismo tiempo podríamos tener fallos técnicos en los algoritmos que se aseguran de supervisar el rendimiento del sistema y que no hayan actores maliciosos ni sospechosos dentro. Y si alguno de estos cae o queda fuera de funcionamiento pueden producirse cambios dentro de nuestro sistema de los cuales no nos percatemos.
Con estos algoritmos nos referimos a los que se encargan de supervisar los registros y controlar que actores hay en determinado momento y compararlo con un momento distinto (Comparar y analizar distintas snapshots del sistema). 
Ya que puede ser muy difícil de llevar a cabo por un solo humano por lo cual se implementan estos algoritmos que se encargan de ir evaluando parámetros predefinidos que permiten al supervisor tener una idea de que es sospechoso y que puede ser potencialmente peligroso dentro del sistema (múltiples ingresos en distintas cuentas desde una misma ip o múltiples ingresos a una cuenta desde distintas ips) muy parecido a realizar un análisis de bitácora del sistema.

**Comment by VlackVist** [comment]
No entiendo la tarea desmarcada por lo que se encuentra incompleta. Solicito más detalle sobre ese punto para poder llevarlo a cabo y completar esta issue. Por ahora doy finalizada esta issue mientras recibo una respuesta
