### ISSUE TITLE
(Feature - Frontend) Boton logo

### ISSUE THREAD

**Issue by zkodah** [TSSW2024/Sprint-3#5]
## Descripción
Se trabajará en el botón principal de la aplicación que será el de al medio

## Tareas
* [x] Caja gratis: Implementar esta opción en el ovarlay
* [x] Caja Pagada: Implementar esta opción en el ovarlay
* [x] Caja gratis Desarrollo I: Al seleccionar Caja gratis se creará una vista con el título de la caja (Ver figma) y genere una caja
 
* [x] Caja Gratis Desarrollo II : Se implementan 2 botones 

1. Botón [Abrir] = Si se clickea se hará una animación donde se mostrarán las monedas contenidas en la caja 
2. Botón [Gratis] = se verá un Modal con las opciones que contiene esta caja y el porcentaje de cada  una
* [x] Caja Pagada Desarrollo  I :  Al seleccionar Caja Pagada se creará una vista con el título de la caja (Ver figma) y genere una caja
* [x] Caja Pagada Desarrollo  II :  Se implementan 2 botones 

1. Botón [Abrir] = Si se clickea se hará una animación donde se mostrarán las monedas contenidas en la caja 
2. Botón [$$$] = se verá un Modal con las opciones que contiene esta caja y el porcentaje de cada  una

> Todo cambio se tendrá que informar al PO para así tener un registro y validarlo.
Para tener una idea ver el Figma

## Fecha de Vencimiento
Se ha definido la fecha de entrega para el día 19-05-2024

**Comment by SmnZin** [comment]
ya hice commit para la implementacion per en el mensaje no se referencio bien esta issue, pero lo importante que ta ready la tarea

**Comment by zkodah** [comment]
Queda colocarla imagen del logo en el botón de al medio y el valor ganado. ejoejoejoejoejo

**Comment by zkodah** [comment]
Se quiere agregar un nuevo botón al lado del girar con la opción de poder simular la ruleta.
