### ISSUE TITLE
(Spike - Qa) Investigacion sobre pruebas automatizadas

### ISSUE THREAD

**Issue by enocksama** [TSSW2024/Sprint-3#7]
## Descripción
Se requiere que el equipo de QA realice una investigación sobre las pruebas automatizadas para nuestra aplicación en desarrollo. El objetivo es identificar las mejores prácticas, herramientas y enfoques para la implementación efectiva de pruebas automatizadas en el proceso de desarrollo.

## Tareas
* [x] Parte 1: Investigar y documentar los diferentes tipos de pruebas que pueden ser automatizadas, como pruebas de unidad, pruebas de integración, pruebas de sistema y pruebas de aceptación automatizadas.
* [x] Parte 2: Identificar cuáles de estos tipos de pruebas son más adecuados para nuestra aplicación y cómo pueden ser integradas en nuestro proceso de desarrollo.
* [x] Tarea 3: Investigar, comparar las herramientas de automatización y evaluar las características, capacidades y limitaciones de cada herramienta y recomendar la más adecuada para nuestras necesidades.

> 

## Fecha de Vencimiento
Se ha definido la fecha de entrega para el día 19-05-2024

**Comment by VlackVist** [comment]
[Sprint 3 (1.0).docx](https://github.com/TSSW2024/Sprint-3/files/15301654/Sprint.3.1.0.docx)

Estos dias he investigado distintos puntos pero por ahora adjunto la documentación de la primera tarea, la cual consistía en investigar los tipos de pruebas, y para que sirven cada una de estas (Pruebas aceptación, unitarias, integración, etc.)

**Comment by VlackVist** [comment]
Respecto a las pruebas que pueden adecuarse a nuestra aplicación, tenemos que tener claro que todas las pruebas mencionadas en la documentación son aplicables a nuestra aplicación simplemente se debe escoger el enfoque más adecuado acorde a la situación.
Es decir, si queremos aplicar pruebas unitarias es viable y podemos aplicarlo en cosas como el sistema de registro e inicio de sesión. O el testeo de campos visuales o trabajos correspondientes al Frontend. 
Para las pruebas de integración podemos aplicarlo a cosas como verificar que la información que se ingresa en un campo visual como puede ser una contraseña sea registrada y guardada en la base de datos con los respectivos protocolos de seguridad.
Para la prueba de sistema puede ser aplicada en algo similar como probar el sistema de registro de usuario y verificar que cuando se crea un usuario se asigne todo en la base de datos respetando los respectivos ids que pueden ser usado como keys primarias o foráneas. 
Y para las pruebas de aceptación automatizadas sería lo ideal aplicarlo al momento de tener la aplicación finalizada ya que con esta podemos simular múltiples interacciones del punto de vista del usuario con nuestra aplicación y buscar errores o delimitadores que no estén establecidos o se hayan podido pasar por alto al levantar el sistema.

En resumen, dependiendo del enfoque que busquemos dar a las pruebas podemos usar cualquiera de ellas siempre cuando sea la que más nos acomode como equipo y al contexto dado.

**Comment by VlackVist** [comment]
[Sprint 3 (Spike 'Investigación sobre pruebas automatizadas').docx](https://github.com/TSSW2024/Sprint-3/files/15393312/Sprint.3.Spyke.Investigacion.sobre.pruebas.automatizadas.docx)

El documento adjunto tiene toda la información relacionada al desarrollo de la Spike. Cada punto relevante de cada tarea se dejó anotado como comentario en este issue. 

Cabe concluir que existen muchas herramientas para llevar a cabo la automatización de pruebas. Y herramientas enfocadas a nuestro entorno también existen varias que incluyen tanto flutter como GCP por lo cual podemos escoger la que más nos acomode tanto técnicamente como en capacidad monetaria. Ya que algunas aplicaciones no son de código abierto y pueden requerir algún tipo de pago para ser utilizadas o implementadas posteriormente. 

Hay incluso aplicaciones como Github Actions que nos ayudan a realizar pruebas automatizadas utilizado directamente nuestro repositorio de Github.
