### ISSUE TITLE
(Feature - Backend) Pub/sub

### ISSUE THREAD

**Issue by zkodah** [TSSW2024/Sprint-3#9]
## Descripción
Se desea trabajar en conjunto con el infraestructura para generar un Pub/Sub

## Tareas
* [x] Consumir :  Consumir el Pub/sub de infratructura
* [x] Mensajes:  Implementa una función procesarMensaje que contiene la lógica para manejar los mensajes recibidos
* [x] cierre:  Maneja el cierre de la conexión con el servidor NATS Streaming de manera adecuada.
* [x] Conectar :  Se conecta a un NATS Streaming Server utilizando un cluster ID y un client ID

> Trabajar en conjunto con el infraestructura

## Fecha de Vencimiento
Se ha definido la fecha de entrega para el día 19-05-2024

**Comment by ItaloRojas** [comment]
He hecho lo que he podido pero no puedo avanzar en la feature por problemas con los permisos en el gcp.
Me tira mensajes asi 
2024/05/14 22:17:09 Failed to publish message: rpc error: code = PermissionDenied desc = User not authorized to perform this action.
Esto me dificulta bastante por que no me deja verificar si es que funciona mi codigo :(

**Comment by zkodah** [comment]
Comprendo, hoy veremos tu asunto en el sprint Chek para tener una solución .
